# Assignment 5, Question 6: Data Transformation

**Points: 20**

Transform and engineer features from the clinical trial dataset.

## Setup

In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import utilities
from q3_data_utils import load_data, clean_data, transform_types, create_bins, fill_missing

df = load_data('data/clinical_trial_raw.csv')
print(f"Loaded {len(df)} patients")

# Prewritten visualization functions for transformation analysis
def plot_distribution(series, title, figsize=(10, 6)):
    """
    Create a histogram of a numeric series.
    
    Args:
        series: pandas Series with numeric data
        title: Chart title
        figsize: Figure size tuple
    """
    plt.figure(figsize=figsize)
    series.hist(bins=30)
    plt.title(title)
    plt.xlabel('Value')
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.show()

def plot_value_counts(series, title, figsize=(10, 6)):
    """
    Create a bar chart of value counts.
    
    Args:
        series: pandas Series with value counts
        title: Chart title
        figsize: Figure size tuple
    """
    plt.figure(figsize=figsize)
    series.plot(kind='bar')
    plt.title(title)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

Loaded 10000 patients

## Part 1: Type Conversions (5 points)

1. Convert 'enrollment_date' to datetime using the `transform_types()` utility
2. Convert categorical columns ('site', 'intervention_group', 'sex') to category dtype
3. Ensure all numeric columns are proper numeric types
4. Display the updated dtypes

In [45]:
# TODO: Type conversions
# 1. Use transform_types() to convert enrollment_date to datetime
# 2. Convert categorical columns ('site', 'intervention_group', 'sex') to category dtype
# 3. Ensure all numeric columns are proper numeric types
# 4. Display the updated dtypes using df.dtypes

df_copy = df.copy()
type_mappings = {
    "enrollment_date": "datetime",
    "site": "category",
    "intervention_group": "category",
    "sex": "category"}
df_copy = transform_types(df_copy, type_mappings)

print("Data types after transformation:")
print(df_copy.dtypes)

df_copy

Data types after transformation:
patient_id                    object
age                            int64
sex                         category
bmi                          float64
enrollment_date       datetime64[ns]
systolic_bp                  float64
diastolic_bp                 float64
cholesterol_total            float64
cholesterol_hdl              float64
cholesterol_ldl              float64
glucose_fasting              float64
site                        category
intervention_group          category
follow_up_months               int64
adverse_events                 int64
outcome_cvd                   object
adherence_pct                float64
dropout                       object
dtype: object

,patient_id,age,sex,bmi,enrollment_date,systolic_bp,diastolic_bp,cholesterol_total,cholesterol_hdl,cholesterol_ldl,glucose_fasting,site,intervention_group,follow_up_months,adverse_events,outcome_cvd,adherence_pct,dropout
0,P00001,80,F,29.3,2022-05-01,123.0,80.0,120.0,55.0,41.0,118.0,site b,Control,20,0,No,24.0,No
1,P00002,80,Female,NaN,2022-01-06,139.0,81.0,206.0,58.0,107.0,79.0,Site A,CONTROL,24,0,No,77.0,No
2,P00003,82,Female,-1.0,2023-11-04,123.0,86.0,172.0,56.0,82.0,77.0,SITE C,treatment b,2,0,Yes,70.0,No
3,P00004,95,Female,25.4,2022-08-15,116.0,77.0,200.0,56.0,104.0,115.0,Site D,treatment b,17,0,No,62.0,No
4,P00005,95,M,NaN,2023-04-17,97.0,71.0,185.0,78.0,75.0,113.0,site e,Treatmen A,9,0,yes,NaN,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P09996,72,Male,23.2,2022-04-11,122.0,73.0,182.0,54.0,92.0,97.0,site c,TREATMENT B,21,0,No,20.0,No
9996,P09997,100,Female,28.9,2023-02-10,124.0,78.0,157.0,56.0,70.0,102.0,Site C,control,11,0,No,57.0,No
9997,P09998,78,F,23.8,2023-11-05,110.0,63.0,154.0,69.0,71.0,114.0,Site C,treatment a,2,1,No,77.0,No
9998,P09999,86,F,27.0,2022-08-27,139.0,98.0,196.0,38.0,119.0,126.0,SITE A,CONTROL,16,0,no,63.0,No
9999,P10000,67,Female,29.4,NaT,134.0,83.0,197.0,51.0,117.0,128.0,Site A,TREATMENT A,22,0,Yes,48.0,No

## Part 2: Feature Engineering (8 points)

Create these new calculated columns:

1. `cholesterol_ratio` = cholesterol_ldl / cholesterol_hdl
2. `bp_category` = categorize systolic BP:
   - 'Normal': < 120
   - 'Elevated': 120-129
   - 'High': >= 130
3. `age_group` using `create_bins()` utility:
   - Bins: [0, 40, 55, 70, 100]
   - Labels: ['<40', '40-54', '55-69', '70+']
4. `bmi_category` using standard BMI categories:
   - Underweight: <18.5
   - Normal: 18.5-24.9
   - Overweight: 25-29.9
   - Obese: >=30

In [46]:
# TODO: Calculate cholesterol ratio

df_copy["cholesterol_ratio"] = df_copy["cholesterol_ldl"] / df_copy["cholesterol_hdl"]

df_copy

,patient_id,age,sex,bmi,enrollment_date,systolic_bp,diastolic_bp,cholesterol_total,cholesterol_hdl,cholesterol_ldl,glucose_fasting,site,intervention_group,follow_up_months,adverse_events,outcome_cvd,adherence_pct,dropout,cholesterol_ratio
0,P00001,80,F,29.3,2022-05-01,123.0,80.0,120.0,55.0,41.0,118.0,site b,Control,20,0,No,24.0,No,0.745455
1,P00002,80,Female,NaN,2022-01-06,139.0,81.0,206.0,58.0,107.0,79.0,Site A,CONTROL,24,0,No,77.0,No,1.844828
2,P00003,82,Female,-1.0,2023-11-04,123.0,86.0,172.0,56.0,82.0,77.0,SITE C,treatment b,2,0,Yes,70.0,No,1.464286
3,P00004,95,Female,25.4,2022-08-15,116.0,77.0,200.0,56.0,104.0,115.0,Site D,treatment b,17,0,No,62.0,No,1.857143
4,P00005,95,M,NaN,2023-04-17,97.0,71.0,185.0,78.0,75.0,113.0,site e,Treatmen A,9,0,yes,NaN,Yes,0.961538
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P09996,72,Male,23.2,2022-04-11,122.0,73.0,182.0,54.0,92.0,97.0,site c,TREATMENT B,21,0,No,20.0,No,1.703704
9996,P09997,100,Female,28.9,2023-02-10,124.0,78.0,157.0,56.0,70.0,102.0,Site C,control,11,0,No,57.0,No,1.250000
9997,P09998,78,F,23.8,2023-11-05,110.0,63.0,154.0,69.0,71.0,114.0,Site C,treatment a,2,1,No,77.0,No,1.028986
9998,P09999,86,F,27.0,2022-08-27,139.0,98.0,196.0,38.0,119.0,126.0,SITE A,CONTROL,16,0,no,63.0,No,3.131579
9999,P10000,67,Female,29.4,NaT,134.0,83.0,197.0,51.0,117.0,128.0,Site A,TREATMENT A,22,0,Yes,48.0,No,2.294118

In [47]:
# TODO: Categorize blood pressure

df_copy["bp_category"] = np.where(df_copy["systolic_bp"] < 120, "Normal",
                              np.where(df_copy["systolic_bp"] < 130, "Elevated", "High"))

**Note:** The `create_bins()` function has an optional `new_column` parameter. If you don't specify it, the new column will be named `{original_column}_binned`. You can use `new_column='age_group'` to give it a custom name.

In [48]:
# TODO: Create age groups

age_bins = [0, 40, 55, 70, 100]
age_labels = ["<40", "40-54", "55-69", "70+"]

df_copy = create_bins(df_copy, "age", age_bins, age_labels, "age_group")

In [49]:
# TODO: Create BMI categories

#4. `bmi_category` using standard BMI categories:
 #  - Underweight: <18.5
  # - Normal: 18.5-24.9
   #- Overweight: 25-29.9
   #- Obese: >=30

df_copy["bmi_category"] = np.where(df_copy["bmi"] < 18.5, "Underweight",
                                np.where(df_copy["bmi"] < 25, "Normal",
                                         np.where(df_copy["bmi"] < 30, "Overweight", "Obese")))

## Part 3: String Cleaning (2 points)

If there are any string columns that need cleaning:
1. Convert to lowercase
2. Strip whitespace
3. Replace any placeholder values

In [51]:
# TODO: String cleaning

df_copy["intervention_group"] = df_copy["intervention_group"].str.strip().str.lower().str.replace("_", " ")
df_copy["site"] = df_copy["site"].str.strip().str.lower().str.replace("_", " ").str.replace("  ", " ")
df_copy["sex"] = df_copy["sex"].str.strip().str.lower().map({
    "f": "female",
    "m": "male",
    "female": "female",
    "male": "male"})

## Part 4: One-Hot Encoding (5 points)

Create dummy variables for categorical columns:
1. One-hot encode 'intervention_group' using `pd.get_dummies()`
2. One-hot encode 'site'
3. Drop the original categorical columns
4. Show the new shape and column names

In [53]:
# TODO: One-hot encoding

encoded_df = pd.get_dummies(
    df_copy, 
    columns=["site", "intervention_group"], 
    prefix=["site", "intervention"])

encoded_df

,patient_id,age,sex,bmi,enrollment_date,systolic_bp,diastolic_bp,cholesterol_total,cholesterol_hdl,cholesterol_ldl,...,site_site c,site_site d,site_site e,intervention_contrl,intervention_control,intervention_treatmen a,intervention_treatment b,intervention_treatment a,intervention_treatment b,intervention_treatmenta
0,P00001,80,female,29.3,2022-05-01,123.0,80.0,120.0,55.0,41.0,...,False,False,False,False,True,False,False,False,False,False
1,P00002,80,female,NaN,2022-01-06,139.0,81.0,206.0,58.0,107.0,...,False,False,False,False,True,False,False,False,False,False
2,P00003,82,female,-1.0,2023-11-04,123.0,86.0,172.0,56.0,82.0,...,True,False,False,False,False,False,False,False,True,False
3,P00004,95,female,25.4,2022-08-15,116.0,77.0,200.0,56.0,104.0,...,False,True,False,False,False,False,False,False,True,False
4,P00005,95,male,NaN,2023-04-17,97.0,71.0,185.0,78.0,75.0,...,False,False,True,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P09996,72,male,23.2,2022-04-11,122.0,73.0,182.0,54.0,92.0,...,True,False,False,False,False,False,False,False,True,False
9996,P09997,100,female,28.9,2023-02-10,124.0,78.0,157.0,56.0,70.0,...,True,False,False,False,True,False,False,False,False,False
9997,P09998,78,female,23.8,2023-11-05,110.0,63.0,154.0,69.0,71.0,...,True,False,False,False,False,False,False,True,False,False
9998,P09999,86,female,27.0,2022-08-27,139.0,98.0,196.0,38.0,119.0,...,False,False,False,False,True,False,False,False,False,False
9999,P10000,67,female,29.4,NaT,134.0,83.0,197.0,51.0,117.0,...,False,False,False,False,False,False,False,True,False,False

## Part 5: Save Transformed Data

Save the fully transformed dataset to `output/q6_transformed_data.csv`

In [ ]:
# TODO: Save transformed data
# df_transformed.to_csv('output/q6_transformed_data.csv', index=False)